name: CI/CD for Backend and Frontend

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building and testing Backend
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install Maven dependencies
      - name: Install Dependencies
        run: ./mvnw dependency:resolve

      # Step 4: Build the Spring Boot application
      - name: Build Backend
        run: ./mvnw clean package

      # Step 5: Run unit tests for Backend
      - name: Run Backend Tests
        run: ./mvnw test

  # Job for building and testing Frontend
  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install frontend dependencies
      - name: Install Frontend Dependencies
        run: npm install

      # Step 4: Run unit tests for Frontend
      - name: Run Frontend Tests
        run: npm test

      # Step 5: Build the React application
      - name: Build Frontend
        run: npm run build
